const countryLanguagesMap = {
  // 东亚与东南亚
  CN: ["zh-Hans"],
  TW: ["zh-Hant"],
  HK: ["zh-Hant", "en"],
  MO: ["zh-Hant", "pt"],
  SG: ["zh-Hans", "en", "ta", "ms"],
  MY: ["ms", "zh-Hans", "ta", "en"],
  JP: ["ja"],
  KR: ["ko"],
  VN: ["vi"],
  TH: ["th"],
  ID: ["id"],
  MM: ["my"],

  // 南亚
  IN: ["hi", "en", "ta", "bn", "ur"],
  PK: ["ur", "en"],
  BD: ["bn"],
  LK: ["ta", "si"],
  NP: ["ne"],
  AF: ["fa", "ps"],
  IR: ["fa"],

  // 中东与北非
  SA: ["ar"],
  AE: ["ar", "en"],
  EG: ["ar"],
  IQ: ["ar", "ku"],
  JO: ["ar"],
  LB: ["ar", "fr"],
  SY: ["ar"],
  MA: ["ar", "fr"],
  DZ: ["ar", "fr"],
  SD: ["ar"],

  // 欧洲
  RU: ["ru"],
  UA: ["uk", "ru"],
  BY: ["ru", "be"],
  KZ: ["ru", "kk"],
  PL: ["pl"],
  CZ: ["cs"],
  RO: ["ro"],
  HU: ["hu"],
  TR: ["tr"],
  GR: ["el"],
  CY: ["el", "tr"],
  DE: ["de"],
  AT: ["de"],
  CH: ["de", "fr", "it"],
  FR: ["fr"],
  BE: ["fr", "nl", "de"],
  NL: ["nl"],
  IT: ["it"],
  ES: ["es"],
  PT: ["pt"],
  GB: ["en"],
  IE: ["en", "ga"],
  FI: ["fi", "sv"],
  SE: ["sv"],
  NO: ["no"],
  DK: ["da"],
  LI: ["de"],

  // 美洲
  US: ["en", "es"],
  CA: ["en", "fr"],
  MX: ["es"],
  AR: ["es"],
  CO: ["es"],
  CL: ["es"],
  PE: ["es"],
  BR: ["pt"],
  SR: ["nl"],

  // 非洲
  KE: ["sw", "en"],
  TZ: ["sw", "en"],
  UG: ["sw", "en"],
  RW: ["rw", "sw", "en", "fr"],
  CD: ["fr", "sw"],
  AO: ["pt"],
  MZ: ["pt"],
  MG: ["fr"],
  SN: ["fr"],
  ET: ["am"],

  // 大洋洲
  AU: ["en"],
  NZ: ["en", "mi"],
  FJ: ["en", "hi"],
  PG: ["en"],
  MU: ["en", "fr", "hi"]
};
